### ISSUE TITLE
DID YOU RIP THIS OFF FROM MY IDEA????

### ISSUE THREAD

**Issue by Hardwaregore** [TechDudie/ode#1]
HOW DARE YOU RIPOFF SelfHostedGIT!!!!!!! @TechDudie

**Comment by TechDudie** [comment]
huh? i think Mr. Linus Torvalds had the idea first

pretty ironic that you're complaning about a git knockoff when you made a git knockoff, and whats more, you're complaning about it on the real git

**Comment by TechDudie** [comment]
u know Victor (Vector) from EL? he said to SirAlexBigBrain, "You can run, but a bomber plane can keep up with you."
he also said other sus stuff

**Comment by Hardwaregore** [comment]
# ITS NOT A GIT KNOCKOFF!!!!!! ITS A `U I   W R A P P E R`

**Comment by TechDudie** [comment]
# ITS NOT A GIT KNOCKOFF!!!!!! ITS A `U I W R A P P E R`

**Comment by TechDudie** [comment]
perfect
